name: Django

on:
push:
  branches:
   - '**'
pull_request:
  branches:
    - '**'
jobs:
  build:


    runs-on: ubantu-latest
    strtegy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: action/checkout@v3
    - name: set up python ${{matrix:python-version}}
      uses: action/setup-python@v3
      with: 
        python-version: ${{matrix:python-version}}
    - name: Install Depenndencies
      run: |
        phython -m pip Install --upgrade pip
        pip Install -r requirements.txt
    - name: Run Test
      run: |
       pytest
